
[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.normal]
family = "SauceCodePro NF"
style = "Regular"

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mode = "Vi"
mods = "Control"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.97
option_as_alt = "Both"

[general]
live_config_reload = true
